version: '3.1'
services:
    mariadb:
      image: mariadb
      container_name: mariadb
      restart: always
      environment:
        MARIADB_ROOT_PASSWORD: 1234
        MARIADB_DATABASE: 'node'
        MARIADB_USER: 'user'
        MARIADB_PASSWORD: 1234
      ports:
        - 3306:3306      
      volumes:
        - ./mariadb/data:/var/lib/mysql

    nodeserver:
        build:
            context: ./app
        ports:
            - "8081:8081"

    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"
